# Generated by Django 5.2.14 on 2026-05-16 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visitante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_puesto', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('lista_espera', 'En lista de espera'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='lista_espera', max_length=15)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emprendedor')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feria')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('emprendedor', 'feria')},
            },
        ),
    ]
