# Generated by Django 5.2.14 on 2026-06-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_emprendedor_usuario_alter_visitante_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_reseña', models.DateTimeField(auto_now_add=True)),
                ('emprendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emprendedor')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feria')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.visitante')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_reseña'],
                'unique_together': {('visitante', 'feria', 'emprendedor')},
            },
        ),
    ]
