# Generated by Django 5.2.14 on 2026-06-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_resenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resenia',
            options={'ordering': ['-fecha_resenia'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.RenameField(
            model_name='resenia',
            old_name='fecha_reseña',
            new_name='fecha_resenia',
        ),
    ]
